
title: EGPGV 2022
email: gpapers@egpgv.org
baseurl: ""
url: "http://egpgv.org"

# --- site config ---

description: > 
  The Eurographics Symposium on Parallel Graphics and Visualization in conjunction with EuroVis 2022, Rome, Italy, June 13, 2022

navigation:
 - title: Home
   url: index.html
 # - title: Program
 #   url: program.html
 # - title: Presentation and Final Submission Information
 #   url: presenters.html 
 # - title: Call for Papers
 #   url: call-for-papers.html
 # - title: Call for Posters
 #   url: call-for-posters.html
#  - title: Supporters
#    url: supporters.html
# - title: Important Dates
#   url: important-dates.html
 # - title: Organization
 #   url: organization.html

# --- end site config ---

# build settings
markdown: kramdown

plugins: 
#  - jekyll-last-modified-at
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - misc
  - archive/previous
  - s3_website.yml
  - .travis.yml
  - vendor

collections: 
  pages:
    output: true
    permalink: /:path:output_ext

